accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('auth/', views.AuthRedirect.as_view(), name='check-auth'),
    path('edit/', views.update_profile, name='edit'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('log_out/', views.log_out, name='log_out')
]

fontcrawler/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.HomeRedirect.as_view()),
    path('home/', views.home, name='home'),
    path('fonts/', views.FontListView.as_view(), name='fonts'),
    path('add_font/', views.add_font, name='add_font'),
    path('about/', views.AboutView.as_view(), name='about')
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.user.username)


# Creating profile after user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# Updating profile after User model changed
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Font(models.Model):
    user = models.ForeignKey(User, related_name='fonts',
                             on_delete=models.CASCADE, null=True)
    family = models.CharField(max_length=90, blank=True)
    url = models.URLField()
    style = models.CharField(max_length=15, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.family

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'birth_date')

main/forms.py
from django import forms


class ParsePageForm(forms.Form):
    url = forms.URLField(label='Enter page link here', required=True)

accounts/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView

from main.models import Font

from .forms import ProfileForm, UserForm


def _form_errors_to_messages(request, form_errors):
    """Not a view. Converts form errors to django message"""
    for error_text in chain(*form_errors.values()):
        messages.error(request, error_text)


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(
                request,
                username=username,
                password=raw_password)
            login(request, user)
            return redirect('accounts:profile')
        else:
            _form_errors_to_messages(request, form.errors)
            form = UserCreationForm()
    else:
        form = UserCreationForm()
    return render(request, 'registration/sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:profile')
        else:
            _form_errors_to_messages(request, form.errors)
            form = AuthenticationForm()
    else:
        form = AuthenticationForm()
    return render(request, 'registration/sign_in.html', {'form': form})


@login_required
def log_out(request):
    logout(request)
    messages.success(request, "You've been successfully logged out!")
    return redirect('home')


class ProfileView(LoginRequiredMixin, ListView):
    template_name = 'registration/profile.html'
    context_object_name = 'font_list'
    model = Font
    paginate_by = 25

    def get_queryset(self):
        """
            Overrides method to get only objects
            related to current user logged in
        """
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        """
            Overrides method to get context dict
            and extend it
        """
        context = super(ProfileView, self).get_context_data(**kwargs)
        user_form = UserForm(instance=self.request.user)
        profile_form = ProfileForm(instance=self.request.user.profile)
        extra_context = {
            'user': self.request.user,
            'user_form': user_form,
            'profile_form': profile_form
        }
        context.update(extra_context)
        return context


class AuthRedirect(View):
    """Checks if user is authenticated"""

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('accounts:profile')
        else:
            return redirect('accounts:sign_in')


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('accounts:profile')
        else:
            _form_errors_to_messages(request, user_form.errors)
            _form_errors_to_messages(request, profile_form.errors)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'registration/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views.generic import ListView, TemplateView, RedirectView

from accounts.views import _form_errors_to_messages

from .forms import ParsePageForm
from .models import Font
from .tasks import parse_page


@login_required
def add_font(request):
    parse_page.delay(request.user.id, 'http://github.com/')
    messages.success(
        request,
        'Your request will be processed soon, check your profile')
    return redirect('home')


def home(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ParsePageForm(request.POST)
            if form.is_valid():
                url = form.cleaned_data.get('url')
                parse_page.delay(request.user.id, url)
                messages.success(
                    request, 'Your request will be processed soon, check your profile')
            else:
                _form_errors_to_messages(request, form.errors)
        else:
            form = ParsePageForm()
    else:
        form = None
    return render(request, 'main/home.html', {'form': form})


class FontListView(ListView):
    model = Font
    context_object_name = 'font_list'
    paginate_by = 3
    template_name = 'main/font_list.html'


class AboutView(TemplateView):
    template_name = 'main/about.html'


class HomeRedirect(RedirectView):
    pattern_name = 'home'

main/templates/base.html
    <!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Font Crawler{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link href="{% static 'main/fonts/fontconfig.css' %}" rel="stylesheet">
</head>
<body>
    <!--Navigation-->
    {% include 'navbar.html' %}

    <!--Messages-->
    <div class="messages-container">
        {% bootstrap_messages %}
    </div>

    <!--Content-->
    <div class="container">
    {% block content %}{% endblock %}
    </div>

    <!--JS-->
    <script src="{% static 'main/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'main/js/popper.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/main/about.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h1>What is fontcrawler?</h1>
            <p class="lead">FontCrawler is a web application allows you to fetch fonts from other sites</p><br>
            <h1>How to use it?</h1>
            <p class="lead">
                <a href="{% url 'accounts:check-auth' %}">log in</a> and come to
                <a href="{% url 'home' %}">home page</a>. Form for requests should appear.
                <br>
                Then, enter page's link you want to parse and press "Get Fonts" button.
                <br>
                Now, go to your profile to "User Fonts" tab and do whatever you want with those fonts :)
            </p>
            <br>
            <h1>Want to contribute?</h1>
            <p class="lead">
                Visit my page at <a href="https://github.com/olekthunder">github.com</a>
            </p>
        </div>

    </div>
{% endblock %}

main/templates/main/font_cards.html
{% for font in font_list %}
    <div class="card m-auto">
        <div class="card-body text-center">
            <h2 class="card-title text-center">{{ font.family }}</h2>
            {% if font.style %}
                <p class="small" style="color:#6c757d">{{ font.style }}</p>
            {% endif %}
            <p>{{ font.url|truncatechars:100 }}</p>
            <a href="{{ font.url }}" class="btn btn-primary">Download from source</a>
        </div>
    </div>
{% empty %}
    <h2 class="text-center" style="margin: 20px;">No fonts available</h2>
{% endfor %}

main/templates/main/font_list.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center" style="margin: 20px; margin-left: 0;">Latest parsed fonts:</h1>
    <div class="general-font-list">
        {% include 'main/font_cards.html' %}
    </div>
    {% include 'main/pagination.html' %}
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
    <h1 style="margin: 20px; margin-left: 0;">Welcome to the fontcrawler tool!</h1>
    <p class="lead">How can something so small as font, be such a big deal for designers?
        A font does everything from representing the brand, to increasing legibility.</p>
    <p class="lead">Here you can fetch information about fonts used on particular pages</p>
    {% if form %}
        <div class="home-form">
            <form action="{% url 'home' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% bootstrap_field field layout='inline' %}
                {% endfor %}
                {% bootstrap_button 'Get Fonts!' button_type='submit' button_class='btn btn-primary' %}
            </form>
        </div>
    {% else %}
        <p class="lead">Just <a href="{% url 'accounts:check-auth' %}">log in</a> and get back there</p>
    {% endif %}
{% endblock %}

main/templates/main/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation" id="pagination">
        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link" href="?page=1#pagination">First</a></li>
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}#pagination"><</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}#pagination">></a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}#pagination">Last</a></li>
        </ul>
    </nav>
{% endif %}

main/templates/navbar.html
<div class="logo text-center">Font Crawler</div>
    <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container-fluid  justify-content-end">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav text-center">
                <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Main</a></li>
                <li class="nav-item"><a href="{% url 'fonts' %}" class="nav-link">Fonts</a></li>
                <li class="nav-item"><a href="{% url 'accounts:check-auth' %}" class="nav-link">Profile</a></li>
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">About</a></li>
            </ul>
        </div>
        </div>
    </nav>